sudo: true
dist: xenial
services:
  - docker
language: python
python:
  - '3.7'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --upload --pdf SCTR-31.pdf --lsstdoc SCTR-31.tex --env=travis --ltd-product sctr-31"
env:
  global:
    - secure: "0b4JCPpgWj7tY5K1RQ/EGb24C2HdB/vyBp3Zj/o+LKQmye4ke0FPOT6EOj3qpAWZMWTFn0daf1dgsRKQVZDBpC5cD+wbzk5PYCZBjfKHMkHk5iudG7662z6Zs31JFQSMFJrkGT4ifSuRF8JwdY8r5gWRemN2ycrNCRoaGOsWOPsGeGWifnsYJWBsMRKIQCFfJt/oHhDNPXz2aSxhSxhHgMCuJarecxEUf5eSGHwZS/5m0itDMPDH2DXKaTUkxTV2jt6qzin2ra3dcfwIIUSyOvbpOzELdjnIi3JO/k/3HSkevcuxtiKqkYIEDvWfoe0rmqKu3jZDP6sebcsnlij7kGSO7jmfp3vtryfxPf1grbb0FXXd7B4hReCr3sIXNDbnAnWJm0qE5ac/k2MhxkSBIzasTFZFMmTnDUjX5G44ICv24Tp5jEQAetwKUBMYlQ+zwbauyVfU64UmNyTBdzAC5M+bI/php+LJ5OTAaD3IkZz6EnYIl2C9NgOt/Qdij5cEuWXztOHvJaArebtOeZjZnXzTcVM7LuL+fS88zp8gGZAzJBRz7q6cZmwrpjMaRUq9+hBi9nt4rUFZWS/1DnAoYEZd/IpDB9k80NgsMDLuHDobB3+c5xlBCjIUrARX+nCAGdQhGVCF21HueWXeb5FGI+703ItPu/g1z1zQ6ZLEph8="
    - secure: "wndJcf51TyTPZpqwsI0PsHMs3bM2uRz37bSgTEbUQ4u7zkzTEnl2QkhS494ioRJ8c6uOYFp8po/wQ1w/SAb3/yzFKhYiCvo5d820JCjOIvcv7r7CGoui16cK9qN9RbzfaGGjist5sjNiIwLTmJpQQxBPwKVVhvPt/YCBpKYyliMfxxfV4wVc/tldBxjeVvfdeGMyfEd/BMFKh8HnRMv49t44CelZcB23uLWWRg9pIGs85JytkUdAXFRufpDx9grdKHEcMKTCb1IY3NAvpGxnP7dSAfixRLUDRLQcyLw+2iB6DKc7Ye3Z0u+U+X4E26CAEOjbsRi4890XbFSBH9JERcVJdHGJNbtHHKKbcXeHhyRLFmKGxi0DcoEBtLhFQ1YtpV5l3kAfAoNbFHW88NpFUFX1oiminnETfoVkVS83LVXQibWjMuaxlscsn14/5RMNerASrEK8Z01TBN//yzutBLC4MGCDek2h1JhZ4ZDSCMthFp3meXYKko6vkr6XstJ08xiX8D1R35mcsPiQr7kxPEYljHnzJSMQRpOmrK3MoNY8fZ3mP/y/5E321AEt8MLY39BOQ19Ffv44QYmijg63fg8yIOT/dth/UHTIqWurCIZP7f1KCSU/7Cr4O/Rz0IIubXtFXwEKKLRcauXZdIyGc/mPjISk9NWqB5JuH5hAVo8="
